public class GithubOAuthCallout_NoCredential {
	public void callGoogleMaps()
    {
    	/*HttpRequest req = new HttpRequest();
        req.setEndpoint('https://github.com/login/oauth/authorize?client_id=647180d589ad9eae5c4e');
        req.setMethod('GET');
        req.setHeader('Accept', 'application/json');
        req.setHeader('Content-Type', 'application/json');
        Http http = new Http();
        HTTPResponse res = http.send(req);
        System.debug(res.getBody());*/
    }
}